ENV: "development"
PORT: "8081"
DATABASE:
  HOST: "localhost"
  PORT: "3306"
  USER: "root"
  PASSWORD: "123456"
  NAME: "bloom-nft"
  ISMIGRATE: true
JWT:
  SECRET: "a15f0bd8594987889bd9be78e35ec9d4"
  EXPIRE_TIME: 24
  ISSUER: "bloom-nft"
  SUBJECT: "bloom-nft"
  AUDIENCE: "bloom-nft"
  ALGORITHM: "HS256"
IPFS_PINATA:
  UPLOAD_URL: "https://api.pinata.cloud/pinning/"
  VIEW_URL: "https://scarlet-tropical-gayal-772.mypinata.cloud"
  API_KEY: c1d68f4214b7c0a59dc8
  API_SECRET: 194e3893a5b70acf35ad1945e97327321ba7eae7481d1f737ccfe504a941a130
  JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkMzI1M2JhNS00NmVmLTQ3ZjYtYWRhMS1kNmFmMzM2NmU0YTciLCJlbWFpbCI6IjE5ODM4MTA5NzhAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6ImMxZDY4ZjQyMTRiN2MwYTU5ZGM4Iiwic2NvcGVkS2V5U2VjcmV0IjoiMTk0ZTM4OTNhNWI3MGFjZjM1YWQxOTQ1ZTk3MzI3MzIxYmE3ZWFlNzQ4MWQxZjczN2NjZmU1MDRhOTQxYTEzMCIsImV4cCI6MTgwNTQ2NjY0OX0.bMMuZFgxIA53KMf4I4mblteZzlCl7cWK8mfdVNeb4_c
NETWORK:
  RPC_URL: "http://127.0.0.1:8545"
  ACCOUNT_PRIVATEKEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
LISTENER:
  ENABLED: true
  START_BLOCK: 0
  POLL_INTERVAL_SEC: 5
  BATCH_SIZE: 500

