// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bloom-nft/api/handler"
	"bloom-nft/database"
	"bloom-nft/repository"
	"bloom-nft/router"
	"bloom-nft/services"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp 由 Wire 生成实现，返回组装好的 *gin.Engine（具体实现在 wire_gen.go）
func InitializeApp() (*gin.Engine, error) {
	testService := services.NewTestService()
	testHandler := handler.NewTestHandler(testService)
	loginService := services.NewLoginService()
	loginHandler := handler.NewLoginHandler(loginService)
	walletService := services.NewWalletService()
	walletHandler := handler.NewWalletHandler(walletService)
	db := database.ProvideDB()
	nftRepository := repository.NewNftRepository(db)
	nftListRepository := repository.NewNftListRepository(db)
	nftService := services.NewNftService(nftRepository, nftListRepository)
	nftHandler := handler.NewNftHandler(nftService)
	nftOrdersRepository := repository.NewNftOrdersRepository(db)
	nftOrdersService := services.NewNftOrdersService(nftOrdersRepository)
	nftOrdersHandler := handler.NewNftOrdersHandler(nftOrdersService)
	engine := router.SetupRouter(testHandler, loginHandler, walletHandler, nftHandler, nftOrdersHandler)
	return engine, nil
}
